# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bebadjango', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date booked'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bebadjango.Passenger'),
        ),
    ]
