# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bebadjango', '0002_auto_20170723_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date booked')),
                ('amount', models.IntegerField(default=0)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebadjango.Passenger')),
            ],
        ),
    ]
