# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bebadjango', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
